### ISSUE TITLE
srblib.Tabular is not able to load xlsx file.

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/Exam_scheduler#3]
while loading xlsx file, I get the following error

```
xlrd.open_workbook(inp_path)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/srbcheema/srb/extra/Exam_scheduler/.venv/lib64/python3.7/site-packages/xlrd/__init__.py", line 182, in open_workbook
    ignore_workbook_corruption=ignore_workbook_corruption,
  File "/home/srbcheema/srb/extra/Exam_scheduler/.venv/lib64/python3.7/site-packages/xlrd/book.py", line 79, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/home/srbcheema/srb/extra/Exam_scheduler/.venv/lib64/python3.7/site-packages/xlrd/book.py", line 1284, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/home/srbcheema/srb/extra/Exam_scheduler/.venv/lib64/python3.7/site-packages/xlrd/book.py", line 1278, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b',srbchee'
```

**Comment by srbcheema1** [comment]
For now resolution is to use xls file, don't use xlsx file.
